### ISSUE TITLE
Add a CI to build the site

### ISSUE THREAD

**Issue by nhoizey** [nhoizey/nicolas-hoizey.com#100]
Would allow adding content directly from Github interface, update Webmentions without local build, etc.

https://quentin.delcourt.be/blog/2020-02-10_eleventy-gitlab-ci-pipeline/

**Comment by Narno** [comment]
LambCI, une alternative à Travis : https://github.com/lambci/lambci.

Exemple : https://github.com/Narno/narno.com/blob/master/.lambci.json.

**Comment by nhoizey** [comment]
@Narno "5 min max build time" -> I can't use it.

**Comment by Narno** [comment]
I understand :-/

**Comment by nhoizey** [comment]
Build in Netlify already works, but without Webmention checks

**Comment by nhoizey** [comment]
Superseded by #1102
