### ISSUE TITLE
POSSE articles to Dev.to and Medium

### ISSUE THREAD

**Issue by nhoizey** [nhoizey/nicolas-hoizey.com#493]
Thanks @hsablonniere!

https://github.com/hsablonniere/hsablonniere.com/blob/master/tasks/cross-post.mjs

**Comment by hsablonniere** [comment]
I think some stuffs are really specific to my context so I'm not sure we should work on a shared lib but if it makes sense, I would be glad to ;-)

**Comment by nhoizey** [comment]
@hsablonniere I'll check your code and let you know! 👍
