### ISSUE TITLE
Automate images optimisation

### ISSUE THREAD

**Issue by nhoizey** [nhoizey/nicolas-hoizey.com#8]
Run imagemin after image are generated by the picture tag plugin?

**Comment by DirtyF** [comment]
I currently use https://github.com/chrisanthropic/image_optim-jekyll-plugin and I find it convenient.

I don't use the picture tag plugin for now, so you may have to change the output of your current plugin or you can choose to easily customize the .rb file to check for your _posts folder instead.

**Comment by nhoizey** [comment]
Interesting, thanks!

**Comment by nhoizey** [comment]
Done with Cloudinary!
