### ISSUE TITLE
Feed Logo 404

### ISSUE THREAD

**Issue by inetbiz** [nhoizey/nicolas-hoizey.com#826]
https://github.com/nhoizey/nicolas-hoizey.com/blob/main/src/feeds/index.md?plain=1#L8 is that a bug? 404 not found.

**Comment by nhoizey** [comment]
@inetbiz the logo is there in the page: https://nicolas-hoizey.com/feeds/

Why do you think it's a bug? Where do you get a 404 error?

**Comment by inetbiz** [comment]
Rendered as broken image.

**Comment by nhoizey** [comment]
@inetbiz where is it rendered as a broken image? Can you be more specific?

I see the image here: https://nicolas-hoizey.com/feeds/

**Comment by inetbiz** [comment]
I wasn't looking in the right source folder. My mistake.
