### ISSUE TITLE
[Suggestion] Possible improvement in build times

### ISSUE THREAD

**Issue by ashmaroli** [nhoizey/nicolas-hoizey.com#91]
**`optimization`**

If you're looking for ways to improve your site's build times, the following might be helpful for you:

Understandably, `{% asset .. %}` does some processing internally to render the desired markup for you. Let us *assume conservatively* that **1 call to render `{% asset .. %}` per build session** takes `0.1s`..
So, if that 1 tag was in a *layout* that would be used 1000 times (via other layouts, pages and documents), then:
```ruby
0.1s * 1000 = 100s
```
And, if there was *8 calls to the asset-tag* in that layout, then:
```ruby
0.1s * 8 * 1000 = 800s
```
Incidentally, you have such a set up in your *default layout:* 
https://github.com/nhoizey/nicolas-hoizey.com/blob/1cf5e4ce9471dc62ac31a50d903623fce4e98db1/_layouts/default.html#L15-L24

(*How many times is your *default layout* used can be gauged from the `--profile` output*)

*Disclaimer: This entire suggestion is based on *my assumption* that the rendered output from those asset-tags could be manually hard-coded in the layout itself.*

**Comment by nhoizey** [comment]
Thanks a lot for the great suggestion, I will dive into this ASAP!

**Comment by ashmaroli** [comment]
You're welcome. In the event that you feel that the use of `{% asset .. @inline %}` cannot be replaced, you can consider moving the entire block to an *include* an then load that include via the [`jekyll-include-cache` plugin](https://github.com/benbalter/jekyll-include-cache)

**Comment by nhoizey** [comment]
I agree, and I already intended to try this plugin, as shown in #69

**Comment by ashmaroli** [comment]
Bon Chance!! :smiley:

**Comment by nhoizey** [comment]
It looks like it doesn't change much with this:
https://github.com/nhoizey/nicolas-hoizey.com/commit/9d3a8ba55562b26d468ed9f5146b81ae9720da56

But I know most of the build time comes from Webmentions…

**Comment by ashmaroli** [comment]
> It looks like it doesn't change much with this:

Yeah Webmentions is a major drain.. but how does your `--profile` stats look like after this change..?

**Comment by nhoizey** [comment]
A lot of huge build performance improvements since this issue was open and discussed, I think it's safe closing it now.

**Comment by ashmaroli** [comment]
That's good to know, Nicolas.
